name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test install script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and exec installation script
        run: |-
          curl https://raw.githubusercontent.com/tehKapa/dockerstaller/master/install.sh | bash
